---
title: "Research"
layout: single
classes: wide
permalink: /papers/
---

##  Working Papers 
**No Need for Speed: Speed Limit Reductions Do Not Increase Vehicle Robberies**<br/>
<small>[ <a href="javascript:void(0);" onclick="toggleVisibility('no-need-for-speed')">Abstract</a> | [Draft](papers/no-need-for-speed.pdf) ]</small>

<div id="no-need-for-speed" style="display: none; text-align: justify; line-height: 1.2"><small>
I analyze the effect of a widespread speed reduction policy implemented in the city of São Paulo on vehicle robberies. Exploring the staggered nature of the policy implementation, I estimate an event study robust to heterogeneity and different adoptions of the treatment, using crime data on reported
vehicle robberies from 2014 to 2016, for the months before and after the policy’s implementation in 2015. I demonstrate that the overall effect on the treated road segments is either null or, when significant, small and negative, contradicting common concerns that the speed reduction could increase drivers’ exposure to crime. I also conduct analyses of heterogeneity for different subgroups by vehicle type and time of day, and the null results remain consistent.
</small><br><br/></div>

<!-- You can add more papers following the same structure -->



##  Works in Progress






<script>
function toggleVisibility(id) {
  var element = document.getElementById(id);
  if (element.style.display === "none") {
    element.style.display = "block";
  } else {
    element.style.display = "none";
  }
}
</script>
